### ISSUE TITLE
LaTeX: `longtblr` & `talltblr`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#13]

**Comment by vincentarelbundock** [comment]
Oh wow, sorry to be stepping on toes! Had I known that you have this package, I would definitely have proposed a collaboration. Oh well...

Yes, that's exactly right. I think it would be nice for users to have access to long tables. There's current support for tall tables already because whenever we use notes, we call tall table under the hood via dump substitution. https://github.com/vincentarelbundock/tinytable/blob/2989ef433669ac6c22ae6e7580c71f1d8b5db8e3/R/tt_tabularray.R#L73

For long tables, I think it might be worth adding a new `theme` argument value, which would load a different template file:

https://github.com/vincentarelbundock/tinytable/blob/main/R/template.R

Then we would just have to adjust how the `caption` argument modifies the table specifically used. That could be done by calling `style_tt(outer = "caption={blahblahbalh},")`, since I believe that captions are in the "outer" settings block (square brackets) in `longtblr`

**Comment by vincentarelbundock** [comment]
Note to self: `longtblr` should not be wrapped in `\begin{table}

**Comment by vincentarelbundock** [comment]
Closing as duplicate of https://github.com/vincentarelbundock/tinytable/issues/154

**Comment by wklimowicz** [comment]
> Note to self: `longtblr` should not be wrapped in `\begin{table}`

Leaving a note for future users in case they encounter weird behaviour with row spacing with `longtblr`. Turns out that `\begin{table}` resets any spacing commands, for example the one I use:
```tex
\usepackage{setspace}
\doublespacing
```
This meant that when I added `theme_tt("multipage")` and removed `\begin{table}` all my tables suddenly became double spaced, because they didn't have the `table` environment. The neatest solution I've found is adding the following to the document preamble when using multipage/longtblr:

```tex
\usepackage{etoolbox}
\AtBeginEnvironment{longtblr}{\begin{singlespacing}}
\AtEndEnvironment{longtblr}{\end{singlespacing}}
```

I've not seen anyone complain about this behaviour here or on the `tabularray` GitHub, but if it becomes more common it might be worth adding the snippet above to the recommended `tinytable` preamble.

<details>
  <summary>Example Quarto Doc</summary>
  
````md
---
title: longtblr and setspacing
format:
  pdf:
    include-in-header:
      - text: |
         % Tinytable preamble
         \usepackage{tabularray}
         \usepackage{float}
         \usepackage{graphicx}
         \usepackage{codehigh}
         \usepackage[normalem]{ulem}
         \UseTblrLibrary{booktabs}
         \UseTblrLibrary{siunitx}
         \newcommand{\tinytableTabularrayUnderline}[1]{\underline
         {#1}}
         \newcommand{\tinytableTabularrayStrikeout}[1]{\sout{#1}}
         \NewTableCommand{\tinytableDefineColor}[3]{\definecolor{
         #1}{#2}{#3}}
         % Spacing Commands
         \usepackage{setspace}
         \doublespacing
         % Fix Spacing in longtblr
         \usepackage{etoolbox}
         \AtBeginEnvironment{longtblr}{\begin{singlespacing}}
         \AtEndEnvironment{longtblr}{\end{singlespacing}}
---


```{=latex}
\begin{longtblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]},
}                     %% tabularray inner close
\toprule
foo & bar & baz \\
foo & bar & baz \\
foo & bar & baz \\
\bottomrule
\end{longtblr}
```

````
</details>

**Comment by vincentarelbundock** [comment]
Thank @wklimowicz this is very interesting. I added a FAQ page with a version of your explanation. Perhaps it'll be useful to other users.
