### ISSUE TITLE
Hide header row

### ISSUE THREAD

**Issue by Nenuial** [vincentarelbundock/tinytable#228]
I was trying to hide the header row and found in the documentation that `colnames(table) <- NULL` should be used. This is however not possible with tibbles. I could convert the tibble to a simple dataframe, but I'd like to avoid that.

Could it be possible to have a `header = false` argument solve this?

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion.

I try to treat adding a new argument as a large cost, because functions with too many arguments are hard to learn. `tinytable` functions already have too many for my taste. In this case, I'm very hesitant to add a new argument, because it is for a very niche feature, and only for one very specific input format. Especially since there's a very easy worksaround already.

Sorry to disappoint.

**Comment by Nenuial** [comment]
I understand. I don't think the functions have too many arguments. It's either that or more functions, either way, if it's well documented, then it's fine. At least that's my take.
