### ISSUE TITLE
typst: asterisk escape

### ISSUE THREAD

**Issue by gerhardriener** [vincentarelbundock/tinytable#246]
when creating tables with asterisks (like significance stars) they are not escaped leading to following error message in typst rendering

`[typst]: Compiling asterisk-escape.typ to asterisk-escape.pdf...error: unclosed delimiter`

Reprex
```
---
title: "asterisk escape"
format: typst
---

## Quarto to typst
Error message

```{r}
library(modelsummary)
reg <- lm(mpg ~ wt, data = mtcars)
modelsummary(reg, stars = TRUE, output = "tinytable")

```
```

**Comment by marcboschmatas** [comment]
I'm not this package's developer, but I added typst escape characters a few weeks back. This issue is already fixed in the development version, see [here](https://github.com/vincentarelbundock/tinytable/blob/main/R/escape.R).

**Comment by vincentarelbundock** [comment]
Thanks again for that nice contribution, @marcboschmatas .

I'll close this issue now, as it should be resolved, but feel free to comment again if you can't get it to work using the github development version.

FYI, I plan to release a new version to CRAN in the coming weeks, but I have completely re-written the Typst tables code to use the default `#table()` rather than `tablex$()`. I still need to test it a bit more to make sure everything works as expected. (Feel free to give it a try!)

**Comment by tockudex** [comment]
Manually escaping the asterisk with `\*` does the trick.
