### ISSUE TITLE
tbl-subcap doesn't work with Quarto

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/tinytable#261]
Hey @vincentarelbundock, I ran into this minor bug today. Here's a simple MWE that borrows from the [knitr-based example](https://quarto.org/docs/authoring/tables.html#computations) from the Quarto docs.

This (i.e., the original) works:

````
```{r}
#| label: tbl-example
#| tbl-cap: "Example"
#| tbl-subcap: 
#|   - "Cars"
#|   - "Pressure"
#| layout-ncol: 2

library(knitr)
kable(head(cars))
kable(head(pressure))
```
````

But replacing `knitr` with `tinytable` causes the sub-captions to disappear.

````
```{r}
#| label: tbl-example
#| tbl-cap: "Example"
#| tbl-subcap: 
#|   - "Cars"
#|   - "Pressure"
#| layout-ncol: 2

library(tinytable)
tt(head(cars))
tt(head(pressure))
```
````

Sorry for not digging deeper. I'm strapped for time atm. Loving tinytable, though ;-)

**Comment by vincentarelbundock** [comment]
Hmm, this is going to be difficult. I have no idea how Quarto decides where to insert subcaptions in the HTML/LaTeX code. They almost certainly hard-coded regex inserts based on the default `kable()` output, and they don't support `tabularray`.

I'll look into it when I have time, but it may require upstream changes.

**Comment by grantmcdermott** [comment]
Cool cool. No rush from my side.

**Comment by vincentarelbundock** [comment]
I investigated, and it looks like Quarto only support markdown tables with subcaptions. I reported it but won't be able to take any action on this unless LaTeX becomes supported upstream. It's just not technically possible for me.

See here for a workaround where `tinytable` emits markdown code. Of course, that makes us lose all the fancy formatting:

https://github.com/quarto-dev/quarto-cli/discussions/10324

**Comment by vincentarelbundock** [comment]
https://github.com/quarto-dev/quarto-cli/issues/10328

**Comment by vincentarelbundock** [comment]
Re-opening. When this is fixed upstream, it'll probably be necessary to use `theme_tt("tabular")`, and it would be nice to document that somewhere. It's easy, but not necessarily obvious.

**Comment by cscheid** [comment]
(Quarto dev here) Sorry for the inconvenience! We should have a fix in Quarto shortly. 

For the curious: the reason this is failing is that a raw latex tabular without captions is not currently interpreted as a table itself. That's not necessarily a bug in Quarto, but it's clearly something that people will want to do. So we need to teach Quarto to recognize multiple inner cell outputs as potentially subfloats in their own regard. It works with markdown tables because those are Pandoc Table elements, which we did teach Quarto to recognize as subfloats.

In the meantime, you should be able to use the div syntax for crossrefs. I tested the following and it seems to work for me locally:

````
---
format: pdf
---

```{r}
#| echo: false
#| output: false
library(tinytable)
```

::: {#tbl-example layout-ncol="2"}

::: {#tbl-example-1}

```{r}
#| echo: false
tt(head(cars)) |> save_tt("latex") |> knitr::asis_output()
```

Cars

:::

::: {#tbl-example-2}
```{r}
#| echo: false
tt(head(pressure)) |> save_tt("latex") |> knitr::asis_output()
```

Pressure
:::

Example

:::
````

<img width="563" alt="image" src="https://github.com/user-attachments/assets/eae6996a-fa5c-492e-b8f0-9114828ca325">

**Comment by vincentarelbundock** [comment]
This is super cool. Thanks for the workaround!

**Comment by cscheid** [comment]
Hey @vincentarelbundock, the PR has been merged, so this will be soon fixed in the Quarto 1.6 prerelease builds, thanks for the report again.

I'll just note in passing one more thing. You said:

> and they don't support `tabularray`.

If you're having trouble with `tabularray` I'd love to help you debug to figure out if it's an(other!) issue in Quarto. Here's a minimal .qmd that shows `tabularray` working with Quarto in crossref settings:

`````qmd
---
format: pdf
keep-tex: true
include-in-header: 
  text: "\\usepackage{tabularray}"
---

::: {#tbl-example .cell layout-ncol="2" tbl-cap='Example' tbl-subcap='["Cars","Pressure"]'}

::: {.cell-output-display}
```{=latex}
\begin{tblr}{lccr}
\hline
 Alpha & Beta & Gamma & Delta \\
\hline
 Epsilon & Zeta & Eta & Theta \\
\hline
 Iota & Kappa & Lambda & Mu \\
\hline
\end{tblr}
```
:::

::: {.cell-output-display}
```{=latex}
\begin{tblr}{|l|c|r|}
\hline
 Left & {Center \\ Cent \\ C} & {Right \\ R} \\
\hline
{L \\ Left} & {C \\ Cent \\ Center} & R \\
\hline
\end{tblr}
```
:::
:::

See @tbl-example, @tbl-example-1, or @tbl-example-2.
`````

<img width="938" alt="image" src="https://github.com/user-attachments/assets/cf566fd6-d6de-41d9-9838-e4278ec096cb">

**Comment by vincentarelbundock** [comment]
That's fantastic. What a quick turnaround!

I look forward to playing with version 1.6.

And thanks for the correction about `tabularray` vs. `tabular`. All of this is excellent news.

**Comment by vincentarelbundock** [comment]
Thanks to everyone who contributed, and especially the Quarto devs for the upstream improvements that allow us to support this.

A solution is now documented on the website: https://github.com/vincentarelbundock/tinytable/commit/8cc961c605c152e5977e08c327b569e3c136eec5
