### ISSUE TITLE
Line at the bottom of the table misplaced when grouping rows

### ISSUE THREAD

**Issue by ahcombs** [vincentarelbundock/tinytable#324]
Hello--thank you for the phenomenal modelsummary/tinytable workflow! I'm just trying it out for coefficient table creation for the first time and I'm really appreciating the interface. 

I'm using modelsummary 2.1.1 and tinytable 0.3.0.34 (though I also tried the CRAN version of tinytable, 0.3.0, with the same result). I ran into an issue with the placement of the horizontal line that separates the coefficients from the model fit statistics below. When I group rows, the line at the bottom does not shift down to accommodate the new row, and so one of the rows that should have been above it instead ends up below it. Example: 

```{r}
library(modelsummary)
library(tinytable)

carmod <- lm(mpg ~ as.factor(cyl), data = mtcars)

modelsummary(carmod) |> 
  group_tt(
    i = list(
      "Cyl" = 3
    )
  )  |> 
  save_tt("carmod.png")
```

gives the table below, where (1.299) sits below the line instead of above it. The more row groups you add, the more rows sit below the divider line. I tried manually removing the line by setting the "line" argument to NULL or the "line_color" argument to "white" in `style_tt()`, but this didn't work.

![carmod](https://github.com/user-attachments/assets/4127973b-f2ca-45ae-8da9-de7576711684)

**Comment by vincentarelbundock** [comment]
Thanks for taking the time to open this issue, I appreciate it!

Good catch.

I have a pretty good sense of what's going on and an idea for how to fix this, but it's likely to be a bit tricky to implement. Also, life is crazy right now, with conferences and prep for the coming semester, so I might not get to this immediately. I'll ping you as soon as there's a fix.

Cheers

**Comment by ahcombs** [comment]
Awesome; thank you for your quick reply!

**Comment by vincentarelbundock** [comment]
So I thought about this a bit, and it turns out to be harder than I thought. The problem is that `modelsummary()` hard-codes the location of the line *before* `tinytable` adds the new row. And there's really no way for `modelsummary()` to be able to anticipate that the user will later add some rows by post-processing.

So the only solution I can think of requires a little bit of manual handling by the user. I documented it here:

https://modelsummary.com/vignettes/appearance.html#starting-fresh

I'll keep thinking about it, but that might be the only (sub-optimal) solution for a while...

**Comment by ahcombs** [comment]
Good enough for me—thanks so much!
