### ISSUE TITLE
(HTML) `style_tt()` is very slow

### ISSUE THREAD

**Issue by J-Moravec** [vincentarelbundock/tinytable#354]
I have table with ~ 150 rows and I would like to style some columns.

However, when I tried to style a bit too many rows, the `style_tt()` function takes a few minutes.

**Comment by vincentarelbundock** [comment]
Which output format?

**Comment by J-Moravec** [comment]
Html. I will produce mre once I got some time

**Comment by vincentarelbundock** [comment]
I think the HTML template could really use some improvements: https://github.com/vincentarelbundock/tinytable/blob/main/inst/templates/bootstrap.html


Say we try something simple like this:

```r
library(tinytable)
tt(head(iris)) |> style_tt(color = "orange") |> save_tt("example.html")
```

You'll see in the raw HTML that every single cell is styled using a separate line of code, to specify the JS/CSS to apply. I bet that this is *incredibly* inefficient for large tables.

In other formats like LaTeX and Typst, we collect all `style_tt()` calls. Then, when we build the final table, we combine and reconcile styles, using the last one if there are conflicts. Finally, we split `i` and `j` indices into arrays, by groups of cells which share a style.

So if I apply "orange" to all cells of a table, the Typst file will have only one array of indices, and it will apply the styling code only once to the full array. In HTML, we call JS functions for every cell separately, one after the other. I have no proof, but I suspect this is inefficient.

Roadmap to potential improvement:

1. Modify `style_bootstrap.R` to do combination and reconciliation of conflicting styles, like here: https://github.com/vincentarelbundock/tinytable/blob/main/R/style_typst.R#L82
2. Add reconciliation call on build here: https://github.com/vincentarelbundock/tinytable/blob/main/R/build_tt.R#L113
3. Modify `style_bootstrap.R` to insert arrays of `i` and `j` indices, instead of one line per cell.
4. Modify the Javascript functions in the bootstrap template here: https://github.com/vincentarelbundock/tinytable/blob/main/inst/templates/bootstrap.html

This is kind of an ambitious project, but I think it is unavoidable for the future. I hope it will make the HTML faster. It will certainly make the code cleaner.

**Comment by J-Moravec** [comment]
```
library("tinytable")
library("parallel")

sample.data.frame = function(x, size, replace = FALSE, prob = NULL){
    i = 1:nrow(x)
    x[sample(i, size, replace = replace, prob = prob),]
    }

timeit = function(expr, env = parent.frame()){
    tik = Sys.time()
    eval(expr, envir = env)
    tok = Sys.time()
    difftime(tok, tik, units = "secs")
    }

sizes = seq(5, 500)

times_tt = mclapply(
    sizes,
    \(x){
        d = sample.data.frame(iris, size = x, replace = TRUE)
        timeit({tt(d) |> save_tt("html")})
        },
    mc.cores = 16
    ) |> unlist() |> as.numeric()

times_style = mclapply(
    sizes,
    \(x){
        d = sample.data.frame(iris, size = x, replace = TRUE)
        timeit({tt(d) |> style_tt(j = 1, color = "orange") |> save_tt("html")})
        },
    mc.cores = 16
    ) |> unlist() |> as.numeric()

plot(times_style, type = "l", col = "red", lwd = 3)
lines(times_tt, col = "green", lwd = 3)
```

![style_tt_timing](https://github.com/user-attachments/assets/71d7aad8-eaf5-4e03-a96b-45f1a18edbfa)

**Comment by vincentarelbundock** [comment]
lol yeah. we need a refactor.

**Comment by vincentarelbundock** [comment]
Here are two versions of a simple table. `iris_old.txt` is the current output of `tinytable`. Then, `iris_old.txt` is an alternative with a javascript function that loops over arrays to style.

I'm not sure this will really speed things up, but it will *certainly* simplify the code. Unfortunately, it'll be a bit of work to implement so we know.

[iris_new.txt](https://github.com/user-attachments/files/17320485/iris_new.txt)
[iris_old.txt](https://github.com/user-attachments/files/17320486/iris_old.txt)

**Comment by vincentarelbundock** [comment]
This took a while because it ended up requiring a total rewrite the styling engine, for all formats. But at least now we I think we can close this. Somewhat slower with styling, but nowhere near the penalty we got earlier.

![speed](https://github.com/user-attachments/assets/b17cdefd-6342-43ad-9160-c67cd5be6f70)
