### ISSUE TITLE
*Suggestion* Maybe helpful to provide instructions on how to install latex for use with tinytable

### ISSUE THREAD

**Issue by SugarRayLua** [vincentarelbundock/tinytable#397]
Tinytable's ability to export tables to many formats is very helpful!

I realized though when installing that I needed to install Latex to save any table I create to .pdf which wasn't clear to me from the tutorial. Thus, it might be helpful to add a basic set of instructions on how to install Latex for different distributions to be able to save .pdfs from tinytable such as:

Linux(Debian/Ubuntu):
sudo apt install texlive textlive-xetex texlive-science

Mac:
follow instructions on: 
https://www.tug.org/mactex/mactex-download.html

Windows and non-distribution methods for Linux:
https://www.tug.org/texlive/

**Comment by vincentarelbundock** [comment]
Thanks, I added a note to the documentation about LaTeX dependencies. I don't want to include full instructions for every computer setup, because that's a deep rabbit hole and thinks can change, so I don't want to maintain this. But at least now it should be clear that saving to PDF requires a full local latex distribution.

**Comment by SugarRayLua** [comment]
Thank you! :-)
