### ISSUE TITLE
Indent in html tables

### ISSUE THREAD

**Issue by Nenuial** [vincentarelbundock/tinytable#88]
The indent argument in style_tt works quite well in for the PDF format, but seems to be doing nothing in the HTML format.
Is that normal?

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report. This should now be fixed in the Github version.

While you're here, do you have any views on this? https://github.com/vincentarelbundock/tinytable/issues/89

I'm working on integrating images (inline plots) in tables, so we'll want a unit of measure that works for LaTeX, HTML, and makes sense for both text distances and image sizes.

**Comment by Nenuial** [comment]
I can confirm that it now works fine. Thanks!
