### ISSUE TITLE
Make measurement units more consistent across functions: pt, px, em, cm

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#89]

**Comment by Nenuial** [comment]
I see two options for this, either have a consistent unit across all arguments for any length.

Ideally though, I would appreciate if the user could choose the unit. I wouldn't mind if I had to specify the unit myself. For instance to write `indent = "1cm"`.

**Comment by vincentarelbundock** [comment]
Thanks for the input, I appreciate it.

I think for now I'll go with `em`. It works pretty broadly across the board and is easy to understand.

Most importantly that keeps things minimal in the user interface, and simpler on the backend, since I don't have to figure out what inputs are valid (arbitrary strings are dangerous).

**Comment by Nenuial** [comment]
That makes sense. I would however be consistent. I just used the `width` argument in the `style_tt()` function without looking at the documentation and got an error because I was trying `width = 5` and it expects a string.

I'm not sure `em` is the most widely "understood" measure of length. Especially since it's not a fixed length and depends on the font size. But that is probably going to be a tough one. Everybody will most likely have different "favorites".

**Comment by vincentarelbundock** [comment]
Ah yeah, forgot that one, thanks!

And right, it's just a tough one, I think. Maybe I can revisit later as the package matures.
